# Generated by Django 5.2.4 on 2025-07-18 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('student_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('berthday', models.DateField(help_text='格式例如：2025-05-01', verbose_name='出生日期')),
                ('contact_number', models.CharField(max_length=20, verbose_name='联系方式')),
                ('address', models.TextField(verbose_name='家庭住址')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.grade', verbose_name='班级')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生信息',
                'db_table': 'student',
            },
        ),
    ]
